### ISSUE TITLE
Create a file with "ersättare" from the book --> then upload to WIkidata

### ISSUE THREAD

**Issue by salgo60** [salgo60/Wikidata_riksdagen-corpus#115]
**Status: Started**

See data I need #111 

1. Create a load file from the book [Enkammarriksdagen 1971-1993/94](https://www.wikidata.org/wiki/Q111443541) having the data used in #111
2. Use Open refine and 
   1. and new records
   2. update if a WD object already exist

**Comment by salgo60** [comment]
* [X] Anita Brorsson [Q118860600](https://www.wikidata.org/wiki/Q118860600)
* [X] Lars Weinehall [Q6234648](https://www.wikidata.org/wiki/Q6234648)
* [X] Erik Blom [Q118859389](https://www.wikidata.org/wiki/Q118859389)
* [X] Mait Modigh [Q118862441](https://www.wikidata.org/wiki/Q118862441)

**Comment by salgo60** [comment]
### Quality check

* SPARQL find all people on ss 2 and page 1-111


#### QA Riksdagens data
That see if "ersättare" is in the database [Riksdagens Öppna data](https://data.riksdagen.se/personlista/?iid=&fnamn=&enamn=&f_ar=&kn=&parti=&valkrets=&rdlstatus=&org=&utformat=json&sort=sorteringsnamn&sortorder=asc&termlista=)

**Comment by salgo60** [comment]
### Open Issue

Do we have info about substitute?

![image](https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/8a618af7-180f-4fd2-97ae-d25b3ee8990d)

**Comment by salgo60** [comment]
## Ersättare finns ibland som textsträng i Riksdagens Öppna API: se även #60 

* WD [Q5627199](https://www.wikidata.org/wiki/Q5627199)
  * Riksdagens Öppna Data [json](https://data.riksdagen.se/personlista/?iid=148b5bbc-8e67-4e7e-abc7-e8be89c604ac&fnamn=&enamn=&f_ar=&kn=&parti=&valkrets=&rdlstatus=&org=&utformat=xml&sort=sorteringsnamn&sortorder=asc&termlista=)
  
<img width="1064" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/313e7db2-3969-4e36-8945-3c5929f47b9d">

**Comment by salgo60** [comment]
@fredrik1984 what is the status of the file with Swedfish political parties over time...

I have a v/vpk for Ingrid Burman ([Q4941267](https://www.wikidata.org/wiki/Q4941267))

see page 523 in volume 1
<img width="500" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/e64951b5-75f6-470c-b0d4-56847f3487c5">

**Question** how do we translate it to Wikidata?

**Comment by salgo60** [comment]
Gegga
* WD [Q5781968](https://www.wikidata.org/wiki/Q5781968)
* Riksdagen [0480007629014](https://data.riksdagen.se/personlista/?iid=0480007629014&utformat=html) [json](https://data.riksdagen.se/personlista/?iid=0480007629014&utformat=json)

<img width="1255" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/610409c4-3c3e-40e6-bb81-25318a6f0668">

**Comment by fredrik1984** [comment]
We are currently prioritizing i-ort, party will come later (including start/end of MP party belonging). 

Regarding Michael Hagberg above, it is a bit messy. But it seems that the Riksdagen web is more correct. Hagberg is mentioned in this protocol from 1991-09-30: https://www.riksdagen.se/sv/dokument-lagar/?doktyp=prot&q=Michael+Hagberg&st=2&riksmote=1991/92

**Comment by salgo60** [comment]
> We are currently prioritizing i-ort, party will come later (including start/end of MP party belonging).
> 
> Regarding Michael Hagberg above, it is a bit messy. But it seems that the Riksdagen web is more correct. Hagberg is mentioned in this protocol from 1991-09-30: https://www.riksdagen.se/sv/dokument-lagar/?doktyp=prot&q=Michael+Hagberg&st=2&riksmote=1991/92

Thanks do the change you think is mostly correct.... or have it correct on "your" side...

**Comment by salgo60** [comment]
* [Another diff](https://www.wikidata.org/wiki/Talk:Q106350428)

**Comment by salgo60** [comment]
* P1214 = NoValue
<img width="1045" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/df38c28c-0547-4ccc-b40b-26c896e4118a">

* [List No Value](https://w.wiki/6nda)

<img width="1374" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/ef14c2b3-24cc-4f6a-a629-3e68275c17ac">
