### ISSUE TITLE
TO DO Swedish PM error found in WD by Riksdagens-Corpus

### ISSUE THREAD

**Issue by salgo60** [salgo60/Wikidata_riksdagen-corpus#121]
From [#252](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/252#issuecomment-1519741124)
> Ok Here's a list of Wiki IDs causing the member_of_parliament unit test to fail -- it means they're missing the role wd:Q10655178, wd:Q33071890, or wd:Q81531912.
> 
* [x] [Q5581563](https://www.wikidata.org/wiki/Q5581563) Bonde i Fållnäs
* [x] [Q19975949](https://www.wikidata.org/wiki/Q19975949) Ekman i Jönköping senare Stocksund
* <del>[ ] [Q116199773](https://www.wikidata.org/wiki/Q116199773) Gilljam i Stockholm **guess this is wrong**</del>
   * [X]  [Q5759618](https://www.wikidata.org/wiki/Q5759618) Gilljam i Stockholm 
* [x] [Q5771035](https://www.wikidata.org/wiki/Q5771035) Grenholm i Stockholm
* [x] [Q5867622](https://www.wikidata.org/wiki/Q5867622) Gripenstedt i Nynäs senare Revlinge
* [x] [Q117035450](https://www.wikidata.org/wiki/Q117035450) Gustavson i Sala senare Västerås
* <del>[ ] [Q5779431](https://www.wikidata.org/wiki/Q5779431) Gyllenstierna af Lundholm i Bjärsgård **guess this is wrong**</del>
    * [x] [Q5779439](https://www.wikidata.org/wiki/Q5779439)  Gyllenstierna af Lundholm i Bjärsgård
* [x] [Q5782356](https://www.wikidata.org/wiki/Q5782356) Hagerman i Stockholm
* [x] [Q99006280](https://www.wikidata.org/wiki/Q99006280) Hagman i Linköping
* [x] [Q117085828](https://www.wikidata.org/wiki/Q117085828) Hansson i Örebro
* [x] [Q116690088](https://www.wikidata.org/wiki/Q116690088) Hansson i Rättvik
* [x] [Q5789203](https://www.wikidata.org/wiki/Q5789203) Hansson i Klovsta
* [x] [Q117221213](https://www.wikidata.org/wiki/Q117221213) Hansson i Ormastorp
* [x] [Q117221276](https://www.wikidata.org/wiki/Q117221276) Hansson i Vallberga
* [x] [Q5789670](https://www.wikidata.org/wiki/Q5789670) Hansson i Torp
* [x] [Q5797392](https://www.wikidata.org/wiki/Q5797392) Heidenberg i Visby
* [x] [Q5797565](https://www.wikidata.org/wiki/Q5797565) von Heijne-Lillienberg i Edeby
* [x] [Q5801387](https://www.wikidata.org/wiki/Q5801387) Henriksson i Laholm
* [x] [Q5801406](https://www.wikidata.org/wiki/Q5801406) Henriksson i Kolbuxeröd
<del>* [ ] [Q5805033](https://www.wikidata.org/wiki/Q5805033) Hierta i Näsby</del>
   *  [x] [Q5805039](https://www.wikidata.org/wiki/Q5805039) Hierta i Näsby
* [x] [Q117221366](https://www.wikidata.org/wiki/Q117221366) Huss i Ekhult
* [x] [Q5818643](https://www.wikidata.org/wiki/Q5818643) Hygrell i Lycksele
* [x] [Q5823030](https://www.wikidata.org/wiki/Q5823030) Indebetou i Forssa
* [x] [Q5824384](https://www.wikidata.org/wiki/Q5824384) Isaksson i Nygården
* [x] [Q5824491](https://www.wikidata.org/wiki/Q5824491) Isberg i Norrtälje
* [x] [Q5885281](https://www.wikidata.org/wiki/Q5885281) Johansson i Fägerhult
* [x] [Q117221619](https://www.wikidata.org/wiki/Q117221619) Johansson i Rimforsa
* [x] [Q117222379](https://www.wikidata.org/wiki/Q117222379) Johansson i Onsjö senare Larv
* [x] [Q116687298](https://www.wikidata.org/wiki/Q116687298) Johansson i Bronäs
* [x] [Q6140081](https://www.wikidata.org/wiki/Q6140081) Johnsson i Norr-Kärra
* [x] [Q5889587](https://www.wikidata.org/wiki/Q5889587) Johnsson i Remmarlöv
* [x] [Q117222503](https://www.wikidata.org/wiki/Q117222503) Jonasson i Gullaboås
* [x] [Q5891393](https://www.wikidata.org/wiki/Q5891393) Jonsson i Sundsbyn
* [x] [Q5892646)](https://www.wikidata.org/wiki/Q5892646) Josefsson i Halmstad
* [x] [Q5926472](https://www.wikidata.org/wiki/Q5926472) Kunze i Göteborg
* [x] [Q29034014](https://www.wikidata.org/wiki/Q29034014) Lamberg i Ystad
<del>* [ ] [Q40759724](https://www.wikidata.org/wiki/Q40759724) von der Lancken i Kristianstad</del>
   * [x] [Q5933362](https://www.wikidata.org/wiki/Q5933362) von der Lancken i Kristianstad
* [x] [Q5937483](https://www.wikidata.org/wiki/Q5937483) Larsson i Rönnsbol
* [x] [Q5956515](https://www.wikidata.org/wiki/Q5956515) Lindh i Säffle
* [x] [Q111916168](https://www.wikidata.org/wiki/Q111916168) Lindskog i Billinge
* [x] [Q5966083](https://www.wikidata.org/wiki/Q5966083) Lundblad i Eskilstuna
* [x] [Q5966794](https://www.wikidata.org/wiki/Q5966794) Lundgren i Göteborg
* [x] [Q5967728](https://www.wikidata.org/wiki/Q5967728) Lundström i Piteå
* [x] [Q5969231](https://www.wikidata.org/wiki/Q5969231) Låftman i Billingsfors
* [x] [Q5969775](https://www.wikidata.org/wiki/Q5969775) Lönnberg i Linköping
* [x] [Q5985428](https://www.wikidata.org/wiki/Q5985428) Metzén i Skänninge
* <del>[ ] [Q108333808](https://www.wikidata.org/wiki/Q108333808) Montgomery-Cederhielm i Segersjö</del>
   * [x] [Q5992302](https://www.wikidata.org/wiki/Q5992302) Montgomery-Cederhielm i Segersjö
* [x] [Q6010969](https://www.wikidata.org/wiki/Q6010969) Nilsson i Viby
* [x] [Q98393527](https://www.wikidata.org/wiki/Q98393527) Nordenskjöld i Sjögelö
* [x] [Q112036699](https://www.wikidata.org/wiki/Q112036699) Norrby i Åkersberga
* [x] [Q111728193](https://www.wikidata.org/wiki/Q111728193) Ohlsson i Järrestad senare Gladsax o Simrishamn
* [x] [Q6042591](https://www.wikidata.org/wiki/Q6042591) Persson i Tofta
* [x] [Q6160772](https://www.wikidata.org/wiki/Q6160772) Persson i Vä
* [x] [Q6043249](https://www.wikidata.org/wiki/Q6043249) Persson i Häljebol
* [x] [Q117039047](https://www.wikidata.org/wiki/Q117039047) Petersson i Gärestad
* [x] [Q6161303](https://www.wikidata.org/wiki/Q6161303) Petersson i Möllstorp
<del>* [ ] [Q2086269](https://www.wikidata.org/wiki/Q2086269) von Platen i Vettinge</del>
   * [x] [Q6051464](https://www.wikidata.org/wiki/Q6051464) von Platen i Vettinge
* [x] [Q6056573](https://www.wikidata.org/wiki/Q6056573) Printzensköld i Jönköping
* [x] [Q114729447](https://www.wikidata.org/wiki/Q114729447) Risberg i Kållered
* [x] [Q6078545](https://www.wikidata.org/wiki/Q6078545) Rooth i Helsingborg
* [x] [Q6082517](https://www.wikidata.org/wiki/Q6082517) Rudberg i Halltorp
* [x] [Q6084488](https://www.wikidata.org/wiki/Q6084488) Ruthberg i Grisbacka
* [x] [Q6085142](https://www.wikidata.org/wiki/Q6085142) Rydberg i Korsgården
* [x] [Q6166587](https://www.wikidata.org/wiki/Q6166587) Rönblad i Härnösand
* [x] [Q6086793](https://www.wikidata.org/wiki/Q6086793) Rönnberg i Stocked
* [x] [Q6166851](https://www.wikidata.org/wiki/Q6166851) Sahlström i Utterbyn
* [x] [Q6171696](https://www.wikidata.org/wiki/Q6171696) Segerlind i Uddersrud
* [x] [Q6177454](https://www.wikidata.org/wiki/Q6177454) Sjöcrona i Helsingborg
* [x] [Q6168498](https://www.wikidata.org/wiki/Q6168498) Schmidt i Partille
* [x] [Q6169091](https://www.wikidata.org/wiki/Q6169091) von Schoultz i Göteborg
* [x] [Q6178395](https://www.wikidata.org/wiki/Q6178395) Sjögreen i Mariannelund
* [x] [Q6178565](https://www.wikidata.org/wiki/Q6178565) Sjögren i Lund
* [x] [Q6178560](https://www.wikidata.org/wiki/Q6178560) Sjögren i Asarum
* [x] [Q6179348](https://www.wikidata.org/wiki/Q6179348) Skagerberg i Annefors
* [x] [Q117018060](https://www.wikidata.org/wiki/Q117018060) Smedh i Bergkarlås
* [x] [Q6188899](https://www.wikidata.org/wiki/Q6188899) Stenbäck i Kullinge
* [x] [Q6188945](https://www.wikidata.org/wiki/Q6188945) Stendahl i Eldsberga
* [x] [Q6190734](https://www.wikidata.org/wiki/Q6190734) Stjernstedt i Tisslinge
* [x] [Q6190864](https://www.wikidata.org/wiki/Q6190864) Stockenberg i Halmstad
* [x] [Q6194030](https://www.wikidata.org/wiki/Q6194030) Styffe i Stockholm
* [x] [Q6194477](https://www.wikidata.org/wiki/Q6194477) Stånggren i Linköping
* [x] [Q6331198](https://www.wikidata.org/wiki/Q6331198) Sundberg i Haparanda
* [x] [Q6199804](https://www.wikidata.org/wiki/Q6199804) Swartz i Norrköping
* [x] [Q6201341](https://www.wikidata.org/wiki/Q6201341) Säve i Karlstad
* [x] [Q6205904](https://www.wikidata.org/wiki/Q6205904) Tenger i Västervik
* [x] [Q6208993](https://www.wikidata.org/wiki/Q6208993) Thorburn i Uddevalla
* [x] [Q116146163](https://www.wikidata.org/wiki/Q116146163) Thörnberg i Ronneby
* [x] [Q48704901](https://www.wikidata.org/wiki/Q48704901) af Trolle i Karlskrona
* [x] [Q6216096](https://www.wikidata.org/wiki/Q6216096) Trägårdh i Ystad
* [x] [Q6216492](https://www.wikidata.org/wiki/Q6216492) Tufwesson i Lur
* [x] [Q6218905](https://www.wikidata.org/wiki/Q6218905) Uhlén i Malmö
* [x] [Q6228885](https://www.wikidata.org/wiki/Q6228885) Wahlgren i Stora Dicka
* [x] [Q6229360](https://www.wikidata.org/wiki/Q6229360) Walberg i Alingsås
* [x] [Q6230443](https://www.wikidata.org/wiki/Q6230443) Wallén i Nyebro
* [x] [Q27996966](https://www.wikidata.org/wiki/Q27996966) Welin i Herrljunga
* [x] [Q6237369](https://www.wikidata.org/wiki/Q6237369) Westblad i Husby
* [x] [Q6237483](https://www.wikidata.org/wiki/Q6237483) Westerberg i Falköping
* [x] [Q94645211](https://www.wikidata.org/wiki/Q94645211) Wikström i Karlskrona
* [x] [Q6243918](https://www.wikidata.org/wiki/Q6243918) Winborg i Stockholm
* [x] [Q6245359](https://www.wikidata.org/wiki/Q6245359) Witt i Helsingborg
* [x] [Q112133202](https://www.wikidata.org/wiki/Q112133202) Åkerström i Clemensnäs
* [x] [Q26211952](https://www.wikidata.org/wiki/Q26211952) Persson i Bromma
* [x] [Q117426463](https://www.wikidata.org/wiki/Q117426463) Rydén i Växjö

**Comment by BobBorges** [comment]
from catalog.csv:

Q116199773 | Gilljam i Stockholm | Gustaf F | 1:91 | 5:135 | i Stockholm

**Comment by salgo60** [comment]
Band 1:91 --> SPA [sj9PGLAlnmUAAAAAABfNfA](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfNfA) --> Wikidata [
hub.toolforge.org/P4819:sj9PGLAlnmUAAAAAABfNfA?site=wd](https://hub.toolforge.org/P4819:sj9PGLAlnmUAAAAAABfNfA?site=wd) = WD [Q5759618](https://www.wikidata.org/wiki/Q5759618)

<img width="661" alt="image" src="https://user-images.githubusercontent.com/14206509/234045226-ef74b557-25b3-4aec-b62e-613aaccead43.png">

**Comment by BobBorges** [comment]
@salgo60 It's strange about the Q-ID. Do you think it changed or how did we end up with an error?

**Comment by salgo60** [comment]
Looks like a simple mistake both has the same surname...

* [Q5759618 version history](https://www.wikidata.org/w/index.php?title=Q5759618&action=history&offset=&limit=500)
* [Q116199773 version history](https://www.wikidata.org/w/index.php?title=Q116199773&action=history&offset=&limit=500)

**Comment by salgo60** [comment]
@BobBorges another mismatch

**correct**: [Q5805039](https://www.wikidata.org/wiki/Q5805039) Hierta i Näsby

**Comment by BobBorges** [comment]
[Q5933362](https://www.wikidata.org/wiki/Q5933362) updated in known_mps_catalog.csv

**Comment by BobBorges** [comment]
Added basic roles for all of these except Q26211952. Some didn't need to have roles added, but the QIDs were redirect QIDs, so once those were replaced the corpus query works properly.

**Comment by salgo60** [comment]
> Added basic roles for all of these except Q26211952. Some didn't need to have roles added, but the QIDs were redirect QIDs, so once those were replaced the corpus query works properly.

@BobBorges maybe you should add a **precheck** if a record is redirected.... its just to do a get on an URL and se what is returned,,,,

SPARQL [Första/Andra kammaren merges the last 1000 days](https://w.wiki/6eSJ)

[<img width="1346" alt="image" src="https://user-images.githubusercontent.com/14206509/235426014-797196b7-1543-422f-b8db-95b8a214afbc.png">](https://w.wiki/6eSL)

---- 
I walk through the above list a little bit slowly...

**Comment by BobBorges** [comment]
> maybe you should add a precheck if a record is redirected.... its just to do a get on an URL and see what is returned,,,,

@salgo60 I'm working in a somewhat different way, with a python library called pywikibot. I discovered these pages were redirects because my attempt to add a role failed. In data I was working with, there was only a handful, so I just printed the ID to the console when it failed and updated them manually. If it would happen again and there were more instances, I'd definitely automate the fix somehow.

**Comment by salgo60** [comment]
@BobBorges there is also a new [rest API](https://www.wikidata.org/wiki/Wikidata:REST_API) released, @dpriskorn who does more programming than me will visit me tomorrow and I think he prefer python lib [WikibaseIntegrator](https://github.com/LeMyst/WikibaseIntegrator) everyday in the week... let me know if we should have an on.line sessions...

There is also a Notebook instance called [PAWS](https://wikitech.wikimedia.org/wiki/PAWS) were you also can play and get some [code examples](https://wikitech.wikimedia.org/wiki/PAWS/PAWS_examples_and_recipes)....

Let me know if you have questions 
* there is a [Telegram Wikidata group](https://t.me/joinchat/IeCRo0j5Uag1qR4Tk8Ftsg) that is very active...
* [Wikidata weekly newsletter](https://www.wikidata.org/wiki/Wikidata:Status_updates) - [latest issue apr 24](https://www.wikidata.org/wiki/Wikidata:Status_updates/2023_04_24)

**Comment by salgo60** [comment]
FYI @BobBorges 
* good or bad way of cite a book?
* we need to be aware that [Q110346241](https://www.wikidata.org/wiki/Q110346241) has more articles about the same person and the information is not identical....
   * I guess dependent how the sources will be used we easily will introduce some _noice_ and _confusion_ for the researcher
       * my be some guidelines how to quote would make sense dependent how advanced this corpus will be used...

### Paperbook issues with [Q110346241 Two-Chamber Parliament 1867-1970](https://www.wikidata.org/wiki/Q110346241) that they produce more articles not identical for one person...

* [Q6190864](https://www.wikidata.org/wiki/Q6190864) you added - [21:53, 29 April 2023](https://www.wikidata.org/w/index.php?title=Q6190864&oldid=1885220148)‎ [BobBorges](https://www.wikidata.org/w/index.php?title=User:BobBorges&action=edit&redlink=1) [talk](https://www.wikidata.org/w/index.php?title=User_talk:BobBorges&action=edit&redlink=1) [contribs](https://www.wikidata.org/wiki/Special:Contributions/BobBorges)‎

[<img width="914" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/fbe665f3-3ea7-4a9a-9f43-577e41276c88">](https://www.wikidata.org/wiki/Q6190864#P39)

  * [Q6190864](https://www.wikidata.org/wiki/Q6190864),Stockenberg i Halmstad, P Thure G, 2:401, 3:151
     * 3:151 = SPA [sj9PGLAlnmUAAAAAABfpRg](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfpRg)
     
     [<img width="802" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/124d8f0d-442a-464f-9c3c-1b85b1820acf">](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfpRg)
     
     * 2:401 = SPA [sj9PGLAlnmUAAAAAABfnUA](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfnUA)
     
     
     [<img width="802" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/537c4c1a-2400-47ab-9281-3bcacb3cd428">](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfnUA)
     
 ## my conclusion from this one sample
1. [Q110346241 Two-Chamber Parliament 1867-1970](https://www.wikidata.org/wiki/Q110346241) more articles for one person are not identical
1. [Q110346241 Two-Chamber Parliament 1867-1970](https://www.wikidata.org/wiki/Q110346241) books in later volumes dont necessary have the more precise information
1. The way I have added references is assuming that the information is the same if a person has more articles
   1. and I have used as a SPA ref the first one I have found for a person, I havnt checked in the book if the SPA picture is from a specific article for a person

**Comment by BobBorges** [comment]
Thanks @salgo60. I'll pay closer attention to that in the future.

**Comment by salgo60** [comment]
> Thanks @salgo60. I'll pay closer attention to that in the future.

You did correct but as you have maybe seen I start to add the SPA ref in the citations and maybe have added the SPA from the wrong article... 😭  the problem I guess be for people consuming the corpus...

I hope your corpus will add better data with better time precision and easy to check with the TEI protocols... 

----
OT the architect of Wikidata Denny did a very nice video of the development of Wikidata  - [Wikidata the making of ](https://www.youtube.com/watch?v=P3-nklyrDx4)

 The history of Wikidata, from its inception to its creation and the first ten years of operation, up to 2022. Paper was presented at The Web Conference 2023, Special Track on the History of the Web, Austin, TX, USA.

* Paper 10.1145/3543873.3585579 [HTML](https://dl.acm.org/doi/fullHtml/10.1145/3543873.3585579 [pdf](https://dl.acm.org/doi/pdf/10.1145/3543873.3585579)


[<img width="1370" alt="image" src="https://github.com/salgo60/Wikidata_riksdagen-corpus/assets/14206509/810e4450-7178-4ac7-a9aa-9fd9df72f43c">](https://www.youtube.com/watch?v=P3-nklyrDx4)
