### ISSUE TITLE
Ministers with prime minister

### ISSUE THREAD

**Issue by rbbby** [salgo60/Wikidata_riksdagen-corpus#35]
Previously I have used separate queries for ministers and prime ministers. However realizing that when doing so I lose the connection between the prime ministers and their cabinets.

I just found that the cabinets contain their prime ministers together with other ministers in the cabinets has part property. While I am able to query for all ministers in this way, I am not sure / cant find a resource on how to extract their minister role together with start and end dates while doing so.

Any suggestions on how to query for data of the form:
cabinet, person_wiki_id, role, start, end

For example:
Löfven I, Q5581337, Minister for Housing, 18 April 2016, 25 April 2016

**Comment by salgo60** [comment]
@rbbby  Call me if I misunderstanding you +46-735152802 or close it of this is what you want

* [SPARQL](https://w.wiki/4qHM)
```
SELECT ?cabinetLabel ?roll  (REPLACE(STR(?RollQ), ".*Q", "Q") AS ?rollQ) ?minister (REPLACE(STR(?MinisterQ), ".*Q", "Q") AS ?ministerQ) ?start ?end
WHERE {
  values ?cabinet   {wd:Q18176361}
  ?cabinet p:P527 ?pMinister.
  ?pMinister ps:P527 ?MinisterQ
  OPTIONAL{?pMinister pq:P3831 ?RollQ}
  OPTIONAL{?pMinister pq:P580 ?start}
  OPTIONAL{?pMinister pq:P582 ?end}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "sv,en". }
  ?MinisterQ rdfs:label ?minister. Filter(lang(?minister)="sv")
  ?RollQ rdfs:label ?roll. Filter(lang(?roll)="sv")
}
```

**Note:** My quess is that there is no standard how a cabinent is modelled in Wikidata and I feel we have a huge challenge to modell cabinents between countries and say this is same as the german xxx... I guess we need to be better using [skos:closeMatch, exactMatch....](https://www.w3.org/TR/skos-reference/#L4858)

Best is to ask a project like "[Wikidata:WikiProject every politician](https://www.wikidata.org/wiki/Wikidata:WikiProject_every_politician)" if there is a consensus see [the discussion page for what questions people ask](https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_every_politician)

**Comment by rbbby** [comment]
Thanks this was almost exactly what I am looking for. The only additional feature would be to change:
"  values ?cabinet   {wd:Q18176361}" to capture all cabinets of Sweden without listing them all in a values clause.

**Comment by salgo60** [comment]
Lets see what Wikidata has 🚀 

* [SPARQL find Cabinets](https://w.wiki/4qNk) --> Regeringen Edén October 19, 1917 -> Regeringen Andersson November 30, 2021
** [Number ministers per cabinet](https://w.wiki/4qNz)

TBC

**Comment by rbbby** [comment]
Thanks, helped a lot! Managed to modify it to https://w.wiki/4qPpwhich is what I was looking for.
It is a bit unfortunate that so many ministers have missing start-end dates, but I think we will be able to filter them efficiently by using the cabinets start-end dates (I have those in a separate file). I will implement this new data in the corpus now and get back to you if there are any issues.

**Comment by salgo60** [comment]
As not everyone on Wikipedia is a Wikidata geek you often find better information in the Wiki Article e.g. [Regeringen_Branting_III](https://sv.wikipedia.org/wiki/Regeringen_Branting_III)

<img width="856" alt="image" src="https://user-images.githubusercontent.com/14206509/154052514-a7a151e9-92a7-45e3-a59a-00f4f5ca8fde.png">
