### ISSUE TITLE
Tvåkammar-riksdagen 1867-1970 -> Wikidata

### ISSUE THREAD

**Issue by salgo60** [salgo60/Wikidata_riksdagen-corpus#38]
Status: **> [100% done](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38#issuecomment-1360364007)**  [lista todo](https://query.wikidata.org/embed.html#%23title%3A%20Personer%20i%20f%C3%B6rsta%2C%20andra%20kammaren%20utan%20k%C3%A4lla%20Tv%C3%A5kammarRiksdagen%0ASELECT%20distinct%20%3Fperson%20%3FpersonLabel%20%3FsvWiki%20WHERE%20%7B%0A%20%20VALUES%20%3Fmember%20%7B%0A%20%20%20%20wd%3AQ33071890%20%23%20Member%20of%20First%20Chamber%0A%20%20%20%20wd%3AQ81531912%20%23%20Member%20of%20Second%20Chamber%0A%20%20%20%20%23wd%3AQ82697153%20%23%20Member%20of%20the%20Estates%0A%20%20%20%20%23wd%3AQ10655178%20%23%20Member%20of%20the%20Swedish%20Riksdag%0A%20%20%7D%0A%20%20%3Fperson%20wdt%3AP39%20%3Fmember.%0A%20%20values%20%3Fsource%20%20%7Bwd%3AQ110346241%7D%0A%20%20%0A%20%20minus%7B%3Fperson%20p%3AP1343%20%3FnodeSources.%0A%20%20%3FnodeSources%20ps%3AP1343%20%20%3Fsource%7D%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3FsvWiki%20schema%3Aabout%20%3Fperson%20.%0A%20%20%20%20%20%20%3FsvWiki%20schema%3AinLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20%3FsvWiki%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%2Cen%22.%20%7D%0A%7D%0AORDER%20BY%20%3FpersonLabel)...
* digital version of the book available see https://github.com/welfare-state-analytics/riksdagen-corpus/issues/147

see also an idea how a Wikipedia article should reference the book https://github.com/welfare-state-analytics/riksdagen-corpus/issues/148

* list [what we have today with page and volume](https://w.wiki/4$ag) / [optional](https://w.wiki/4$kX) / [optional2](https://w.wiki/4$kZ) / [optional3](https://w.wiki/4$ka)
   * [same but with party](https://w.wiki/53Gf) 
* [ ] **Not done** the goal is to have one WD object and one svWikipedia article for every person. Status today is [abt 3900 PMs in the register list](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt) - Wikidata has 3345 [folk i första och andra kammaren](https://w.wiki/4$qi) - [1700 riksdagsledamöter](https://w.wiki/4$kX) are connected to the book Tvåkammar-riksdagen 1867-1970 but needs cleaning
  * [ ] **Not Done** [file WD <-> matched with unique id in book](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/WD%20Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt) **work in progress** status [1500 matched](https://github.com/salgo60/Wikidata_riksdagen-corpus/commit/340ff19a831dbee7352aec7da9ca553b53a01979)
  
* [X] [Register över riksdagsmannabiografier band 1-5](https://github.com/salgo60/Wikidata_riksdagen-corpus/blob/main/data/Register%20%C3%B6ver%20riksdagsmannabiografier%20band%201-5.txt) **Work in progress cleaning**version 0.1 **has 3815 persons**
   * [X]  next manual check
* [ ] template in sv:Wikipedia [Malldiskussion:TvåkammarRiksdagen](https://sv.wikipedia.org/wiki/Malldiskussion:Tv%C3%A5kammarRiksdagen) is maybe developed

* [Wikidata timeline](http://minancestry.blogspot.com/2022/03/spa-tidslinje.html) 

[<img width="1207" alt="image" src="https://user-images.githubusercontent.com/14206509/161382051-8961dfae-6286-440a-ab93-5083fd12160d.png">](http://minancestry.blogspot.com/2022/03/spa-tidslinje.html) using the [Histropedia tool](http://histropedia.com/)

## Misc
* [svWIkipedia article with ref Norra Begravningsplatsen for a Swedish PM but WD miss this info](https://petscan.wmflabs.org/?psid=21788353)
* [sanity check](https://w.wiki/4$fw ) WD Tvåkammar-riksdagen 1867-1970
### Maybe worth to test
* use [NER](https://en.wikipedia.org/wiki/Named-entity_recognition) in the OCR:ed text in SPA ex. 
** https://portrattarkiv.se/endpoints/portraits.php?id=sj9PGLAlnmUAAAAAABge6w is WD [Q5930866](https://www.wikidata.org/wiki/Q5930866) --> we could check what is inside the parenthesis of field **PortraitBioText** and check that with what is in Wikidata

<img width="479" alt="image" src="https://user-images.githubusercontent.com/14206509/161417126-0878ba9b-ac13-463d-81fc-64c7a4441ee7.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/14206509/161417172-0d34d985-77e9-4ab2-ad33-b9fb86d92555.png">

 fh 1910-1911, n 1912-1930

<img width="946" alt="image" src="https://user-images.githubusercontent.com/14206509/161417245-5fca8344-eb22-429a-bc55-70188c4986f5.png">

### Good to have tool Entity Explosion browser plug-in ###
* [Wikidata:Entity_Explosion](https://www.wikidata.org/wiki/Wikidata:Entity_Explosion)
* [video](https://youtu.be/zn24opgQw_c)

**Comment by salgo60** [comment]
When no party is mentioned in "Tvåkammar-riksdagen 1867-1970 " I add 

<img width="843" alt="image" src="https://user-images.githubusercontent.com/14206509/163568808-7d3c59e3-21b9-489d-8d1f-8ed5eec2d0d8.png">

<img width="269" alt="image" src="https://user-images.githubusercontent.com/14206509/163568843-2425557a-5833-4da0-9651-aba2797888a7.png">

* [in the book ](https://portrattarkiv.se/details/sj9PGLAlnmUAAAAAABfOzQ)
<img width="522" alt="image" src="https://user-images.githubusercontent.com/14206509/163568923-7927508a-86f3-49de-ad88-d735ae01a5f4.png">


* SPARQL  [?person rdf:type wdno:P102.   #missing party value](https://w.wiki/547E)

**Comment by salgo60** [comment]
* [ ] create a cleaning software to see that all references are "complete" see [T308831](https://phabricator.wikimedia.org/T308831) and update what is missing

**Comment by salgo60** [comment]
<img width="948" alt="MLRiksdagstryck" src="https://user-images.githubusercontent.com/14206509/187056803-dfc206e1-6014-4789-8f12-78db06df8fef.png">

**Comment by salgo60** [comment]
[lång video](https://www.youtube.com/watch?v=YNILvlAW3SM) om hur saker kopplas ihop idag med WIkidata, Wikipedia, bilder och kan kopplas ihop ännu mera, se även [ProjectOutdoorGyms/issues/120](https://github.com/salgo60/ProjectOutdoorGyms/issues/120#issuecomment-1242183361)

**Comment by salgo60** [comment]
* [Video](https://www.youtube.com/watch?v=aCNDQ9clVsA) Hur kvaliten i Wikidata kollas mot boken Tvåkammar-riksdagen 1867-1970

**Comment by salgo60** [comment]
Stänger denna som ej slutförd

**Comment by salgo60** [comment]
* SPARQL [First Chamber Second Chamber missing p1343 = "Two-Chamber Parliament 1867-1970"](https://w.wiki/77ST)

**Comment by fredrik1984** [comment]
> SPARQL [First Chamber Second Chamber missing p1343 = "Two-Chamber Parliament 1867-1970"](https://w.wiki/77ST)
status 2023 08 22 [missing 382](https://w.wiki/7JV9)

Ok, thank you @salgo60 for working on this! Let us know when you are done or encounter some problems!

**Comment by salgo60** [comment]
@fredrik1984 easier if you call me but no more action planned 0735152802 I try to get some better status

**Comment by fredrik1984** [comment]
Ok, I might be able to call you over lunch today and check the status!
