### ISSUE TITLE
Government cabinets being different instances

### ISSUE THREAD

**Issue by rbbby** [salgo60/Wikidata_riksdagen-corpus#47]
We had a bug in the corpus where ministers were not able to be matched. It turns out the reason was that government cabinets can be either instances of "Government of Sweden" or "Cabinet" (with country being in Sweden). This is now handled for the corpus but should probably not be this way in Wikidata. 

Examples:
- Palme I Cabinet, Q10650456
- Erlander III Cabinet, Q10650426

**Comment by salgo60** [comment]
Thanks @rbbby I normally check other objects like Q109712556 "Regeringen Scholz" but an open Knowledge graph with 14000 active people with 14000 different purposes has weakness :blush:

* I did a bad fix and added both...
  * [Q10650456](https://www.wikidata.org/wiki/Q10650456)
  * [Q10650426](https://www.wikidata.org/wiki/Q10650426)
