### ISSUE TITLE
Riksmötet 1983-1984

### ISSUE THREAD

**Issue by salgo60** [salgo60/Wikidata_riksdagen-corpus#86]
Fil [skapad](https://docs.google.com/spreadsheets/d/1XPiKQ9kl78qvn1-mhBYcDIR4tjMtlA90BA2f4sWz7lA/edit#gid=1511535787)

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/14206509/208398650-22a80c82-4029-4f46-a3d0-c0a707ad26ea.png">

Plan enligt [Issue 57#issuecomment-1311051413](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/57#issuecomment-1311051413)

* [x] I en kolumn finns Riksdagsdokument id = P8433 som skulle "översättas till "Qnummer i Wikidata"
   * [x] För RefProtokoll skapa URL [hub.toolforge.org/P8433:G8095?format=json](https://hub.toolforge.org/P8433:G8095?format=json) dvs- där används verktyget [HUB hemsida](https://hub.toolforge.org/)
Hämta JSON -->
   * [x] Parse JSON with 
   > value.parseJson()['origin']["qid"]
   * [x] Reconciliation av utskott till WD 
   
   <img width="919" alt="image" src="https://user-images.githubusercontent.com/14206509/208409475-6e88ef0c-5cf4-4201-80aa-3fdafb9b60b3.png">   
   
   * [x] Upload to Wikidata new data
   
   <img width="777" alt="image" src="https://user-images.githubusercontent.com/14206509/208409151-676f2c2b-c11a-4b4e-814c-87f364ae042e.png">

**Comment by salgo60** [comment]
**1. New column using Add coilumn by....**

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/14206509/208400165-e3d7eccf-e8c3-4a29-b212-fa2b4c9dab85.png">

**Comment by salgo60** [comment]
Ny kolumn skapad

<img width="578" alt="image" src="https://user-images.githubusercontent.com/14206509/208403157-5ccf7cc2-b5a8-4097-8ced-681b6225d85a.png">

**Comment by SchermanJ** [comment]
Jäklar vad du jobbar fort!

**Comment by salgo60** [comment]
> Jäklar vad du jobbar fort!

hm Nu krascha min maskin .... kör för mycket udda applikationer...

**Comment by salgo60** [comment]
Jobb snurrar chansar och stänger denna

**Comment by salgo60** [comment]
[Riksmöte-84-85.openrefine.tar.gz](https://github.com/salgo60/Wikidata_riksdagen-corpus/files/10275083/Riksmote-84-85.openrefine.tar.gz)
